## Resolución de sistema de ecuaciones con GAUSS

Dado el sistema de ecuaciones se genera una _matriz compacta_, con la que se busca tener una triangulo formado por **ceros** en la parte inferior de matriz de manera que esta quede triangular.

$$\begin{Bmatrix}
2x - y + 3z = 5\\ 
2x + 2y + 3z = 7\\ 
-2x + 3y      = -3
\end{Bmatrix}$$

Ahora reescribiendo el sistema como una _matriz compacta_ tendríamos que:

$$\begin{bmatrix}
2 & -1 & 3 & 5\\ 
2 & 2 & 3 & 7\\ 
-2 & 3 & 0 & -3
\end{bmatrix}$$

Ahora comencemos a operar para obtener nuestra **matriz triangular**.

In [1]:
import numpy as np

In [2]:
C = np.array([[2.0, -1.0, 3.0, 5.0], 
[2, 2, 3, 7],
[-2, 3, 0, -3]])
T = np.copy(C)

print(T)

[[ 2. -1.  3.  5.]
 [ 2.  2.  3.  7.]
 [-2.  3.  0. -3.]]


In [3]:
T[2] = T[2] + T[1]
print(T)

[[ 2. -1.  3.  5.]
 [ 2.  2.  3.  7.]
 [ 0.  5.  3.  4.]]


In [4]:
T[1] -= T[0]
print(T)

[[ 2. -1.  3.  5.]
 [ 0.  3.  0.  2.]
 [ 0.  5.  3.  4.]]


In [5]:
T[2] = T[2] - (5.0/3.0)*T[1]
print(T)

[[ 2.         -1.          3.          5.        ]
 [ 0.          3.          0.          2.        ]
 [ 0.          0.          3.          0.66666667]]


Con estas operaciones conseguimos tener nuestra matriz triangular. Nuestro resultado fue el siguiente: 


$$C = \begin{bmatrix}
2 & -1 & 3 & 5\\ 
2 & 2 & 3 & 7\\ 
-2 & 3 & 0 & -3
\end{bmatrix} \Rightarrow T = \begin{bmatrix}
2 & -1 & 3 & 5\\ 
0 & 3 & 0 & 2\\ 
0 & 0 & 3 & 0
\end{bmatrix}$$

Ahora también podríamos haber utilizado las funciones de **numpy** para obtener un matriz triangular directamente, para esto era necesario utilizar la función `np.triu()`.

In [6]:
Tn = np.triu(C)
print(Tn)

[[ 2. -1.  3.  5.]
 [ 0.  2.  3.  7.]
 [ 0.  0.  0. -3.]]


para este punto podrías obtener manualmente los valores de cada una de las variables recostruyendo el sistema de ecuaciones, tendríamos que:


$$\begin{Bmatrix}
2x - y + 3z = 5\\ 
3y = 2\\ 
3z = \frac{2}{3}
\end{Bmatrix}$$

De esto podemos obtener que:
$$\begin{Bmatrix}
x = \frac{5}{2}\\\ 
y = \frac{2}{3}\\ 
z = \frac{2}{9}
\end{Bmatrix}$$

Que este mismo resultado podríamos encontrar utilizando directamente la función de `np.linalg.solve()`.

In [7]:
a = C[:,0:3]
b = C[:,3]
print(a)
print(b)

[[ 2. -1.  3.]
 [ 2.  2.  3.]
 [-2.  3.  0.]]
[ 5.  7. -3.]


In [8]:
s = np.linalg.solve(a, b)
print(s)

[2.5        0.66666667 0.22222222]
